name: night
description: Night phase for a popular board game
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.5
  peerdart: ^0.5.2
  fluttertoast: ^8.0.8
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/hitler.jpg
    - assets/fascist.jpg
    - assets/liberal.jpg
    - assets/secret.jpg
    - assets/shnight.png
    - assets/lobby.png
    - assets/lobbycode.png